### ISSUE TITLE
VULNERABLE or UNKNOWN?

### ISSUE THREAD

**Issue by TechCiel** [speed47/spectre-meltdown-checker#109]
![image](https://user-images.githubusercontent.com/22628325/35265341-d5411350-005a-11e8-8466-3fef487da488.png)
I ran this script on OpenVZ VPS just now and having myself confused.
Does the script have enough info indiacting 5715 and 5754 as VULNERABLE but 5753 as UNKNOWN?

**Comment by speed47** [comment]
Could you run the script again with `-v` ? I'd like to see which kernel parts the script did find (vmlinux and/or System.map and/or the kernel config).

**Comment by TechCiel** [comment]
![image](https://user-images.githubusercontent.com/22628325/35310382-20239a32-00ec-11e8-9803-deaa8c13ae5e.png)
@speed47

**Comment by speed47** [comment]
Thanks. It turns out you have no kernel image, no config and no System.map.
So the script has almost nothing to work with, I've pushed a new version that correctly reports unknown for variant 2 & 3 when this is the case!

**Comment by TechCiel** [comment]
Thanks 0v0

**Comment by speed47** [comment]
Released in v0.33
