### ISSUE TITLE
echo_cmd error with latest commit 

### ISSUE THREAD

**Issue by GreggJensen** [speed47/spectre-meltdown-checker#113]
with the latest commit (acf12a6d2d0187acc1ec9c028d9eb632f8259804) there is a problem with the and echo_cmd at line 899.  The error is:

$ sudo ./spectre-meltdown-checker.sh  --batch
./spectre-meltdown-checker.sh: 899: ./spectre-meltdown-checker.sh: -ne: not found

which appears to be that the echo_cmd at that point in the file is not defined (looks like something needs to call __echo before the check_cpu function is called.

**Comment by speed47** [comment]
Oops, interestingly I didn't bump into that bug during my tests on several machines :(
The fix is easy enough, instead of lazy-initializing the $echo_cmd var, I'll just init it at the beggining unconditionally. Doing...

**Comment by speed47** [comment]
Should be fixed in latest master.

**Comment by GreggJensen** [comment]
Confirmed that this is fixed.
