### ISSUE TITLE
Report broken microcode releases

### ISSUE THREAD

**Issue by knweiss** [speed47/spectre-meltdown-checker#115]
Intel's early (initial) microcode releases for the Spectre v2 mitigation were broken
and therefore [deprecated](https://newsroom.intel.com/news/root-cause-of-reboot-issue-identified-updated-guidance-for-customers-and-partners/).

The checker could **detect and report the broken early microcode releases** (and maybe also link to the fixed microcodes when they become available).

The following posting contains the version info: http://lkml.iu.edu/hypermail/linux/kernel/1801.2/06349.html

I.e. there will probably be a blacklist in the Linux kernel, too.

**Comment by speed47** [comment]
Good idea. I'll start a branch about that. Even if the kernel does have a blacklist, if it's in this script, it'll be able to report these problematic microcodes regardless of the kernel version running

**Comment by speed47** [comment]
Pushed to `bad_ucode` branch

**Comment by knweiss** [comment]
@speed47 Great! I've tried the `bad_ucode` code successfully on a system with a bad microcode version and saw the error message.

What to you think about printing the detected microcode version in the error message?

**Comment by speed47** [comment]
I could be of some help so that people know what to look, done

**Comment by speed47** [comment]
Merged to master / v0.33
