### ISSUE TITLE
The vulnerability status is kernel-only - what about user space?

### ISSUE THREAD

**Issue by knweiss** [speed47/spectre-meltdown-checker#119]
I'm wondering if `spectre-meltdown-checker` should emphasize in its status output that it is "only" reporting the **kernel's** vulnerability status.

Example: Mitigating Spectre Variant 2 in the kernel with retpoline won't mitigate any **user space** application. They remain vulnerable i.e. user space process A may still be able to read memory of user space process B.  (That's why [Fedora will probably retpoline the world in a mass rebuild](https://lwn.net/Articles/744423/).)

IMHO the checker output should indicate this in its output because _a false sense of security is worse than no security at all._ ;-)

A possible change could look like this: Change
```
STATUS: VULNERABLE  (IBRS hardware + kernel support OR kernel with retpoline are needed to mitigate the vulnerability)
```
into
```
KERNEL STATUS: VULNERABLE  (IBRS hardware + kernel support OR kernel with retpoline are needed to mitigate the vulnerability)
```

Maybe also add an explicit user space status line:
```
USER SPACE STATUS: APPS MAY STILL BE VULNERABLE
```

**Comment by speed47** [comment]
I don't want to change the output of the script to explain this, however the disclaimer (advertised at each launch on the last line) is probably the proper place do to that. Will do.

**Comment by xftroxgpx** [comment]
Hey, any idea what the gcc flags we are supposed to be using for Spectre v2 mitigation for user spage programs?
And if anyone finds out, would they be included in the `--disclaimer` output ?

I'm currently using (but have no idea if good):
` -mindirect-branch=thunk -mindirect-branch-register`

<details>

```bash
$ gcc --target-help|grep -E mindirect\|thunk
  -mfunction-return=          Convert function return to call and return thunk.
  -mindirect-branch-register  Force indirect call and jump via register.
  -mindirect-branch=          Convert indirect call and jump to call and return
                              thunks.
  Known indirect branch choices (for use with the -mindirect-branch=/-mfunction-return= options):
    keep thunk thunk-extern thunk-inline
$ gcc --version
gcc (GCC) 7.2.1 20180116
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#I'm on ArchLinux
```
</details>

**Comment by knweiss** [comment]
@xftroxgpx As far as I know `-mindirect-branch=thunk -mindirect-branch-register` should be fine. The latter flag is required for compatibility with [Control-Flow Enforcement Technology (CET)](https://software.intel.com/sites/default/files/managed/4d/2a/control-flow-enforcement-technology-preview.pdf) feature of coming Intel CPUs.

FWIW: You can use the **Compiler Explorer** website to see and compare the effect of the various flags of various compilers and compiler version: [Example](https://godbolt.org/g/4BWR2u)

(Side note: Microsoft's new [`/Qspectre` flag for MSVC](https://blogs.msdn.microsoft.com/vcblog/2018/01/15/spectre-mitigations-in-msvc/) is a mitigation for Spectre variant **1**. However, GCC's and LLVM's new flags are a mitigation for Spectre variant **2**.)

**Comment by speed47** [comment]
I've added a note about userspace in the disclaimer.
About the gcc options to use, I would second what @knweiss says, from my understanding.

**Comment by speed47** [comment]
Closing, as the disclaimer had been updated some versions ago to notify the users about this

**Comment by knweiss** [comment]
FWIW: There's now a kernel patch for **Spectre v2 Userspace-Userspace (or app2app) protection**:
[Linux Readying Spectre V2 Userspace-Userspace Protection](https://www.phoronix.com/scan.php?page=news_item&px=Linux-Spectre-V2-Userspace).

> The default behavior will be for the kernel to decide on "lite" or "strict" behavior. The lite mode enables mitigation for non-dumpable processes while the strict mode protects all user processes. This support can be toggled via the spectre_v2_app2app= kernel configuration.
