### ISSUE TITLE
the result, should I worry?

### ISSUE THREAD

**Issue by dfxi14** [speed47/spectre-meltdown-checker#120]
![spectre_and_meltdown](https://user-images.githubusercontent.com/35186579/35561831-17b9745a-05e4-11e8-8c11-5490cfa27ccf.png)

--------------------------------------
hp pavilion 23 aio

**Comment by speed47** [comment]
You should update your system to get all the fixes the vendor of your OS might have made available.
If after a complete update, you're still marked as vulnerable for all, you should check with said vendor (`deepin`) to see if there's any update planned on their side.
