### ISSUE TITLE
spectre-meltdown-checker.sh: 449: ./spectre-meltdown-checker.sh: 3: parameter not set

### ISSUE THREAD

**Issue by Mbuto** [speed47/spectre-meltdown-checker#124]
Running the script (v0.33+) on Ubuntu 17.10 w/ kernel 4.13.0-32-generic on a Lenovo I3 Skylake, I get the following error:

> spectre-meltdown-checker.sh: 449: ./spectre-meltdown-checker.sh: 3: parameter not set

Any prevoious version worked fine.

Thank you for assistance. Regards

**Comment by speed47** [comment]
Thanks for the report, this should be fixed on the latest commit!

**Comment by Mbuto** [comment]
here I confirm: **FIXED**!
