### ISSUE TITLE
Add a final total STATUS

### ISSUE THREAD

**Issue by jidanni** [speed47/spectre-meltdown-checker#130]
I think many administrators will just look at the last result, and think they "passed  the test OK" if it says:
```
> STATUS:  NOT VULNERABLE  (PTI mitigates the vulnerability)
```
Therefore consider adding a final total status that is the combination of all the other statuses. (Any FAIL then total=FAIL.)

As far as the additional:
```
A false sense of security is worse than no security at all, see --disclaimer
```
It would be best to put that quote elsewhere, lest some think it is part of the result.

**Comment by jidanni** [comment]
Actually the problem is the administrator will only look at the final line,
```
> STATUS:  NOT VULNERABLE  (PTI mitigates the vulnerability)
```
not noticing there are other sections above it...

**Comment by speed47** [comment]
A "final summary" has been implemented in latest commit of `master` branch
