### ISSUE TITLE
Retpoline enabled: NO using Linux 4.15.2

### ISSUE THREAD

**Issue by maurom** [speed47/spectre-meltdown-checker#138]
Running spectre-meltdown-checker with the just-released kernel 4.15.2 reports

```
Spectre and Meltdown mitigation detection tool v0.34

Checking for vulnerabilities on current system
Kernel is Linux 4.15.2 #1 SMP Thu Feb 8 11:16:22 UTC 2018 x86_64
CPU is Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
...
* Mitigation 2
  * Kernel compiled with retpoline option:  YES 
  * Kernel compiled with a retpoline-aware compiler:  YES  (kernel reports full retpoline compilation)
  * Retpoline enabled:  NO 
> STATUS:  NOT VULNERABLE  (Mitigation: Full generic retpoline)
...
```
which is quite strange, because the kernel was compiled with full retpoline and there's no parameter in the command line disabling it. Here's the [full s-m-c report](https://maurom.com/kernel/4.15.2/spectre-meltdown-status-4.15.2.txt) and the command line:

```
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.2 root=UUID=XXXX ro quiet
```

It may be relevant to note that the kernel devs seem to [have removed the _retpoline_ feature bit](https://lkml.org/lkml/2018/1/27/142) from `/proc/cpuinfo`

**Comment by speed47** [comment]
Indeed the kernel devs cleaned up some flags they started to introduce in /proc/cpuinfo, and one of those is `retpoline`. I'll just remove the "retpoline enabled?" test, because for newer kernels, the /sys interface does give the answer anyway, in a more reliable manner than checking in `dmesg`.

**Comment by speed47** [comment]
done in 22cae60 (master branch). Thanks for noticing.

**Comment by maurom** [comment]
Actually, I have to thank you for scripting such a useful tool.

About this change. IMHO it would be nice to retain the Retpoline Enabled check when running s-m-c on older kernels, as some of them do have this feature flag but don't have the /sys/../vulnerabilities interface. Maybe run the /proc/cpuinfo check only if the kversion is 4.YY < X < 4.15.2.

That's just my two pennies' worth; thanks again for the quick fix.
