### ISSUE TITLE
"Known bad microcode list" is outdated. 

### ISSUE THREAD

**Issue by Razerwire** [speed47/spectre-meltdown-checker#139]
The known bad microcode list is outdated, more specifically:
```
		$INTEL_FAM6_SKYLAKE_MOBILE,0x03,0xc2   \
		$INTEL_FAM6_SKYLAKE_DESKTOP,0x03,0xc2  \
```

Intel now advises that 0xc2 microcode updates can be continued to be rolled out:
![image](https://user-images.githubusercontent.com/14997009/35998580-008ea6dc-0d15-11e8-8951-30e6f02577c0.png)

The full Microcode revision guidance dated February 7th 2018 can be found [here](https://newsroom.intel.com/wp-content/uploads/sites/11/2018/02/microcode-update-guidance.pdf):

Furthermore i've updated a Dell E7470 and Dell Precision 7510 with the latest BIOS' updates dated February 6th 2018 and  they both contain microcode 0xc2.

So my suggestion is to remove 0xc2 from the "known bad microcode list",  per the Intel Guidance.

**Comment by speed47** [comment]
Thanks for the pointer!
The list has been updated in commit eb75e51 (master branch)
