### ISSUE TITLE
self-signed certificate on meltdown.ovh domain

### ISSUE THREAD

**Issue by anthonypants** [speed47/spectre-meltdown-checker#159]
I appreciate that your instructions tell users not to blindly pipe scripts from the internet into an interpreter, but asking users to download scripts over http isn't much better.

```
$ wget https://meltdown.ovh -O /tmp/spectre-meltdown-checker.sh
--2018-03-09 11:31:43--  https://meltdown.ovh/
Resolving meltdown.ovh (meltdown.ovh)... 87.98.135.28
Connecting to meltdown.ovh (meltdown.ovh)|87.98.135.28|:443... connected.
ERROR: cannot verify meltdown.ovh's certificate, issued by ‘/CN=nginx’:
  Self-signed certificate encountered.
ERROR: no certificate subject alternative name matches
        requested host name ‘meltdown.ovh’.
To connect to meltdown.ovh insecurely, use `--no-check-certificate'.
```

Here are some instructions for setting up Let's Encrypt with nginx: https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

**Comment by speed47** [comment]
Oh well, I admit I was a bit lazy on this one. Just added it to my SSL handling scripts.
Done. :)
