### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by mike-aungsan** [speed47/spectre-meltdown-checker#161]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

$sudo bash spectre-meltdown-checker.sh
spectre-meltdown-checker.sh: line 13: $'\r': command not found
: invalid signal specificationine 14: trap: EXIT
: invalid signal specificationine 15: trap: INT
spectre-meltdown-checker.sh: line 16: syntax error near unexpected token `$'\r''
'pectre-meltdown-checker.sh: line 16: `exit_cleanup()

**Comment by speed47** [comment]
How did you download the script? The copy you have seems to be damaged/invalid.
Can you try getting it with `wget https://meltdown.ovh -O spectre-meltdown-checker.sh` and check if you still have the error?

**Comment by speed47** [comment]
Assuming that the issue couldn't be reproduced. Please reopen if this is the case.
