### ISSUE TITLE
Checker crashes whole SLES12 SP3 Server

### ISSUE THREAD

**Issue by Pihaar** [speed47/spectre-meltdown-checker#191]
Running the checker under `SLES12 SP3` with the kernel `4.4.126-94.22-default` and the Patchlevel `SUSE-SLE-SERVER-12-SP3-2018-779` leads to a server crash.
I analyzed this issue and found out that the crash happens in the `exit_cleanup()` function while executing `rmmod cpuid`.
After a new server boot I found out that the kernel modules `cpuid` and `msr` are loaded by default. 

Proposal: In order to prevent the crash it would be great to check before with `lsmod` if the two modules are already loaded and if yes that they don't get unloaded after the execution.

**Comment by speed47** [comment]
The script is written in a "leave the system in the state it was before the script was run" intent.
I expected `modprobe` to return an error when trying to load an already-loaded module, but it seems it always reports success in that case, which sets the `insmod_cpuid` variable and wrongly instructs the script to `rmmod` the module on exit, as you've observed, failing the intent.
I wasn't expecting a server to crash when removing the `cpuid` or `msr` modules, however!
Thanks for your PR

**Comment by speed47** [comment]
#192 merged
