### ISSUE TITLE
Misleading text

### ISSUE THREAD

**Issue by angus-p** [speed47/spectre-meltdown-checker#20]
The script states `Kernel compiled with LFENCE opcode inserted at the proper places` - while just checking for a threshold quantity.

There is no validation that the extra opcodes *are* inserted at the proper places

**Comment by speed47** [comment]
You're right, I initially added "proper places" to avoid saying just "with LFENCE opcodes" which wouldn't mean anything: the kernel has already some, and it doesn't mean anything per se.

I'm not really happy with this simple count check, I'm waiting to see how the vanilla patches will look like to come up with something better. This simple count check is originally based on a backported kernel: the openvz one, where they added some LFENCEs themselves.

In the meantime, do you have a better way to say it?

**Comment by viviparous** [comment]
"Checking count of LFENCE opcodes (heuristic to be improved when patches become available)."

**Comment by angus-p** [comment]
for x86_64 modifying the count to test for `lfence` followed by a `pop %rax` is quite a strong indicator - `(objdump -D "$vmlinux" | grep -A 1 lfence | grep -wc 'pop  *%rax')` returns 45 versus 0  (patched 4.4 vs. unpatched 4.11).

Do not have a 32 bit box to test, but suspect there will be a good few `pop %eax`s in a similar location...

**Comment by speed47** [comment]
@viviparous Good idea, just updated the code with this, while we don't have a better check

**Comment by speed47** [comment]
@angus-p To my understanding, vanilla patches are not out yet.

OpenVZ made available their new kernel that fixes the 3 CVEs, they claim (https://openvz.org/Download/kernel/rhel6/042stab127.2).
In the 32 and 64 vmlinux versions there, I can't find any lfence followed by a pop %rax/%eax.

In their patch (also available on the same page), they add
`#define gmb() alternative(ASM_NOP3, "lfence", X86_FEATURE_LFENCE_RDTSC)`
and a lot of `gmb();` a bit everywhere. This results in more "lfence" opcodes than usually, hence the count check.

Which kernel did you use for your test? A custom one with some WIP patches pulled from the LKML or something else?

**Comment by angus-p** [comment]
That was from dump of openSUSE  (running patched4.4 but have an unpatched 4.11 in /boot)

**Comment by angus-p** [comment]
I'd consider this closed with 7222367f04a7c4257228e48b74be8a19facc5991
