### ISSUE TITLE
Spectre v2 marked as not vulnerable while kernel says it is on ARM

### ISSUE THREAD

**Issue by V10lator** [speed47/spectre-meltdown-checker#208]
From the tool:

```
* Mitigation 2
  * Kernel has branch predictor hardening (arm):  YES 
(debug) bp_harden: found 'CONFIG_HARDEN_BRANCH_PREDICTOR=y' in /boot/config-4.4.13-v10-1.1.0
  * Kernel compiled with retpoline option:  NO 
    * Local gcc is retpoline-aware:  NO  (gcc is not installed)
  * Kernel supports RSB filling:  NO 
> STATUS:  NOT VULNERABLE  (Branch predictor hardening mitigates the vulnerability)
```

and from the kernel boot messages:

`[    0.025000] CPU0: Spectre v2: firmware did not set auxiliary control register IBE bit, system vulnerable`

**Comment by V10lator** [comment]
Thanks for explaining. :)

**Comment by rrobgill** [comment]
The final section in "Hardware Check" - "CPU Vulnerability to the speculative execution attack variants", gives the vulnerability status of the hardware, as best as can be determined.

(There does appear to be a false negative at this time on the Cortex A8 as you reported.)
