### ISSUE TITLE
15/JUN/18 spectre spoof your url and change the spectre-meltdown-checker.sh

### ISSUE THREAD

**Issue by manfire** [speed47/spectre-meltdown-checker#211]
DNS SPOOF REDIRECTION !
STOP GIVE DOMAIN NAME LINK - USE DIRECT AND UNIQUE IP SCRIPT URL.
SCRYPT CONTENT - PLEASE ADVICE - BAD COPY OF YOUR SCRYPT IN FILE UPLOA
[spectre-meltdown-checker.zip](https://github.com/speed47/spectre-meltdown-checker/files/2105883/spectre-meltdown-checker.zip)

OS : ubuntu beaver 18 LIVE CD 
FIREFOX

docker.io work
download your scrypt 
docker.io dont work anymore.. it over.

**Comment by manfire** [comment]
[spectre-meltdown-checker.zip](https://github.com/speed47/spectre-meltdown-checker/files/2105885/spectre-meltdown-checker.zip)

**Comment by speed47** [comment]
Hello,

The md5sum of the script in the zip link you gave is the same than the one in the direct script link from github.

To be 100% sure I re-checked the diff between the current version and the version from 1 month ago, there's nothing standing out of the ordinary.

What makes you think there is some malicious content in the script?
