### ISSUE TITLE
Cortex-A7 marked as vulnerable

### ISSUE THREAD

**Issue by 0x9fff00** [speed47/spectre-meltdown-checker#212]
After c181978d7c377bfdbd5eea6bc19dbd98450218af the script marks Cortex-A7 as vulnerable. This CPU is not listed at https://developer.arm.com/support/arm-security-updates/speculative-processor-vulnerability, so it shouldn't be affected by Spectre/Meltdown.
Log: https://gist.github.com/0x9fff00/0f286253faa402590f1a3a1eed97e713

**Comment by speed47** [comment]
Thanks, I've rewritten the logic to be in perfect sync with the ARM statement.
Can you test with the latest master to confirm?

**Comment by 0x9fff00** [comment]
Thanks, it works correctly now.
