### ISSUE TITLE
Filter out Variant 3a and Variant 4 problem for Intel XEON_PHI_KNL and XEON_PHI_KNM CPUs.

### ISSUE THREAD

**Issue by NelsonFu** [speed47/spectre-meltdown-checker#217]
I have Intel XEON_PHI_KNL and XEON_PHI_KNM CPU servers got Variant 3a and Variant 4 check result and failed on Variant 3a.
According to Intel information about these two CPUs do not have Variant 3a and Variant 4 issues. Can you revise checker with Intel design?

**Comment by kode54** [comment]
I have a server with a Yorkfield processor (Q9650) and it is also missing from the Intel advisory for Variants 3a and 4. If it is indeed vulnerable, it would at least be nice if the notice would reflect the fact that microcode updates have stopped for this processor, so an update is never coming.

**Comment by speed47** [comment]
@NelsonFu this should be fixed in latest master, can you confirm?
@kode54 dupe of #205, it has been partly addressed in latest master, and will be completed soon.

**Comment by speed47** [comment]
expected to be fixed, please reopen if this is not the case
