### ISSUE TITLE
mktemp may require 6 Xs on BSD-like distributions such as Slackware

### ISSUE THREAD

**Issue by mradcliffe** [speed47/spectre-meltdown-checker#22]
mktemp on Slackware for instance follows the BSD convention of requiring 6 Xs rather than 3 Xs.

Otherwise an error message occurs:

`mktemp /tmp/blah.XXX`
`mktemp: cannot create temp file /tmp/blah.XXX: Invalid argument`

This should be a simple patch to write, and I'll submit a PR.

**Comment by speed47** [comment]
Merged your PR, thanks!
