### ISSUE TITLE
Does the Intel microcode update 20180703 mitigate variant 3a & 4?

### ISSUE THREAD

**Issue by devhen** [speed47/spectre-meltdown-checker#220]
I expected variant 3a & 4 to finally show as not vulnerable now that I have the latest microcode that Intel just released:

https://downloadcenter.intel.com/download/27945/Linux-Processor-Microcode-Data-File?product=873

But it doesn't. Is this expected? Thanks.

**Comment by rrobgill** [comment]
The 20180703 microcode only includes changes for a handful of processors, listed at the bottom of the page you linked (Some Xeons, Xeon E5s and Xeon E7s and a few very specific models of Core I7.

All others are unchanged from the 20180425 release. My understanding is that the public releases do not yet patch 3a of 4 for any processor.

Intel are still playing catch-up on all of this.

**Comment by devhen** [comment]
I see. Thanks for the info!
