### ISSUE TITLE
Detection of RDCL_NO and SSB_NO flags inside MSR 0x10A

### ISSUE THREAD

**Issue by Githubwoman** [speed47/spectre-meltdown-checker#221]
There is probably an error in routine that checks CPU capabilities.
line 1856: "else:" should be just "else"
or maybe first line should be "#!/bin/bash" and not "#!/bin/sh"

I found a person with a CPU (Apollo Lake) which has RDCL_NO and SSB_NO flags set in MSR 0x10A which returns value of 0x19 (or CPUID function 7 register EDX equal 0x2C000000) but this script didn't indicate that.
Source: https://communities.intel.com/message/556701#556701

**Comment by speed47** [comment]
The line 1856 has just been fixed in b262c40 (master), thanks. The shebang is `#!/bin/sh` and this is not a mistake: extra care is taken to avoid any bashisms in the script, this is also checked by the `shellcheck` linter.

I don't have any up to date CPU to test at hand, but I'll try to simulate the issue see if I can reproduce it. If you happen to find someone having the issue, please ask him/her to run the script in verbose mode (`-v -v`) and paste the output here, this would help!

**Comment by Githubwoman** [comment]
Thanks.
I send this news further. Someone might test this on SSB_NO and RDCL_NO enabled CPU (AFAIK only Apollo Lake SoC CPUID sig 0x506C9).
In the meantime it would be quite easy to test the capabilities routine with "fake" MSR 0x10A output.
I think that substituting read_msr_value="0 0 0 0 0 0 0 25" after read_msr (line #1830) should do the trick.

P.S.
read_msr function could use same treatment as read CPUID (dd "iflag" switch).

**Comment by speed47** [comment]
Faking the read_msr_value and forcefully setting cpuid_arch_capabilities to 1 (as if read_cpuid 0x7 returned the 29th bit of $EDX set, which indicates the MSR 0x10a availability and is checked before we try to read said MSR) seems to give the expected results:

```
  * CPU explicitly indicates not being vulnerable to Meltdown (RDCL_NO):  YES
  * CPU explicitly indicates not being vulnerable to Variant 4 (SSB_NO):  YES
* CPU vulnerability to the speculative execution attack variants
  * Vulnerable to Variant 1:  YES
  * Vulnerable to Variant 2:  YES
  * Vulnerable to Variant 3:  NO
  * Vulnerable to Variant 3a:  YES
  * Vulnerable to Variant 4:  NO
```

Would it be possible that some CPUs do have the ARCH_CAPABILITIES MSR but without advertising it through the proper CPUID bit, preventing the script to test for the MSR?

About the read_msr function, you're right, as I got no negative feedback from the read_cpuid change, I'll propagate it to the read_msr func before releasing the next version.

**Comment by Githubwoman** [comment]
Apollo Lake SoC has 0x2C000000 inside EDX register after calling CPUID funcion 7. That should set cpuid_arch_capabilities to 1.
Maybe right now everything is all right. I didn't get feedback from person who pointed that out.

**Comment by Githubwoman** [comment]
One more tiny thing.
After adding support for SSB_NO flag you forgot to set capabilities_ssb_no=-1 (line #1810) and zero it if there is no ARCH_CAPABILITIES MSR (line #1815).

**Comment by speed47** [comment]
Thanks, fixed the 2 missing inits of capabilities_ssb_no (0f0d103)

**Comment by speed47** [comment]
This is believed to be fixed, and I can't reproduce the issue (it might have been caused by the "else:"  incorrect syntax).
I'm leaving this opened for a while in case somebody with an RDCL_NO microcode can confirm.

**Comment by Githubwoman** [comment]
I haven't got any response from first person who pointed that out. I plan to run Linux Live CD on device with Apollo Lake SoC. I should report back today (in about 12h).

**Comment by speed47** [comment]
@Githubwoman thanks! Just finished some digging following your message, and you are correct: my usage of od messes up the bit order. I could verify that playing around with a known value of my CPU (MSR 0xCE bits 15:8, which is the freq multiplier), using od -u8 fixes the problem, using bitshifts and logical ands on the whole 64 bits register value.
I'll post a branch tomorrow with the theoretical fixes, and if you're then able to test it again, that would be awesome. Thanks again for pointing out this nasty bug!

**Comment by speed47** [comment]
Pushed the fix on top of the `newmsr` branch. Could you @Githubwoman or @knweiss (or both!) test it to confirm?

**Comment by Githubwoman** [comment]
@speed47. Sorry, I couldn't test today that new script.
I tried to use new Live CD Linux (Slax) and it didn't boot from USB drive. Probably because lack of EFI boot manager and Secure Boot enabled.
Tomorrow I will try with Puppy Live CD Linux again.

**Comment by speed47** [comment]
Good, let me know if/when you have tested it. I'd like to wait for your confirmation before releasing v0.39 ;)
