### ISSUE TITLE
Raspberry Pi 3 (ARM v8 model 0xd03) is incorrectly reported as vulnerable to all variants

### ISSUE THREAD

**Issue by hotaru2k3** [speed47/spectre-meltdown-checker#223]
https://www.raspberrypi.org/blog/why-raspberry-pi-isnt-vulnerable-to-spectre-or-meltdown/ says:

> The lack of speculation in the ARM1176, Cortex-A7, and Cortex-A53 cores used in Raspberry Pi render us immune to attacks of the sort.

but spectre-meltdown-checker says:

    $ sudo ./spectre-meltdown-checker.sh --hw-only
    Spectre and Meltdown mitigation detection tool v0.37+
    
    Checking for vulnerabilities on current system
    Kernel is Linux 4.17.10-1-ARCH #1 SMP Thu Jul 26 18:58:28 MDT 2018 aarch64
    CPU is ARM v8 model 0xd03
    
    Hardware check
    * CPU vulnerability to the speculative execution attack variants
      * Vulnerable to Variant 1:  YES
      * Vulnerable to Variant 2:  YES
      * Vulnerable to Variant 3:  YES
      * Vulnerable to Variant 3a:  YES
      * Vulnerable to Variant 4:  YES
    
    A false sense of security is worse than no security at all, see --disclaimer

**Comment by Githubwoman** [comment]
That SoC isn't recognized by this script. Look at line #[405](url=https://github.com/speed47/spectre-meltdown-checker/blob/0f0d103a89097272acc1587cefc38b2b54ea0639/spectre-meltdown-checker.sh#L405).

**Comment by speed47** [comment]
I avoided whitelisting all the non-referenced ARMv8 in the official ARM vulnerability list, to ensure future ARMv8 models wouldn't get whitelisted by error if people would use old versions of the script on them.
However from the ARM current documentation, and if we make the assumption that they always release monotonically increasing part numbers in their new CPUs, we can whitelist all the smaller part numbers that already existed when their list was published.
The `rpi3` branch does just that. Could you try it?

**Comment by speed47** [comment]
> A17 (0xc0e) is marked non-vulnerable to 3a, but ARM says it's vulnerable.
> A15 (0xc0f) is marked vulnerable to 3a, but ARM says it's only vulnerable to 1 and 2, like A8, A9, and A12.

My source for ARM is their table found at https://developer.arm.com/support/arm-security-updates/speculative-processor-vulnerability, which they (hopefully!) keep up to date. I re-checked and to my understanding, the information found there doesn't match what you're reporting. Maybe you have another URL from ARM that contradicts this one?

You're correct about the debug output though, their table changed several times, and even if I did change the code logic, I might have forgot to adjust the debug output. You're also right about the 0x0d7 typo, thanks. Updated the branch with the two debug fixes.

**Comment by hotaru2k3** [comment]
that's the page I was using, but apparently the 3a vulnerability status shows differently on my desktop than on my phone (both using chrome).

**Comment by hotaru2k3** [comment]
that's the page I was using, but when I pulled it up on my phone just now it showed A15 and not A17 as vulnerable to 3a. when I pulled it up on my desktop it showed A17 and not A15 as vulnerable to 3a, the same as what I saw yesterday, but when I hit refresh, it switched. weird.

**Comment by speed47** [comment]
Maybe what you saw on your desktop was the cached version you had locally on your desk, as they changed it several times and I'm not sure they did set the correct headers with a short expiry to ensure browsers don't cache it. Hitting F5 must have forced the refresh most probably!

**Comment by speed47** [comment]
Merged rpi3 branch to master. Please feel free to reopen if needed!
