### ISSUE TITLE
Flatpak or snap

### ISSUE THREAD

**Issue by baimafeima** [speed47/spectre-meltdown-checker#247]
Could this be made available as a flatpak or snap for easy installation without having to build it from source? It could then be used to quickly identify problems on any new distribution one is trying at the moment.

**Comment by sethbergman** [comment]
Due to the way Flatpack handles packaging, this can lead to a large cache being created which quickly inflates to unreasonable sizes. Not only this, but using flatpack requires a large chunk of space to be reserved for it's own file hierarchy. The same could be said for snaps as well AFAIK.

**Comment by speed47** [comment]
This script has been packaged in some distros (Debian/Ubuntu, Red Hat/CentOS at least), but as @richarson said, this is just a shell script, it doesn't even need to be "installed", you can just download it and run it. See the readme file for more information.

**Comment by Matthew-Bradley** [comment]
@speed47 It didn't even occur to me that this script might be packaged! I've been downloading a bunch of new copies each time. Is there anywhere I can find more info on this, like the package names?

**Comment by mattvw** [comment]
@Matthew-Bradley For Red Hat/CentOS, it's in the EPEL repository simply as spectre-meltdown-checker. Just do 'yum install spectre-meltdown-checker' if you have the EPEL repository installed and enabled. Not sure about Ubuntu/Debian.

**Comment by kyodev** [comment]
@Matthew-Bradley
with debian (stable backports | testing | sid), the package name is: `spectre-meltdown-checker`

no pakages for stable or earlier  

today, the version is:
```text
spectre-meltdown-checker | 0.39-1~bpo9+1 | stretch-backports | source, all
spectre-meltdown-checker | 0.39-1        | testing           | source, all
spectre-meltdown-checker | 0.39-1        | unstable          | source, all
```
