### ISSUE TITLE
deprecated SPDX license identifier

### ISSUE THREAD

**Issue by alexvong1995** [speed47/spectre-meltdown-checker#249]
Hello,

The license identifier [GPL-3.0](https://spdx.org/licenses/GPL-3.0.html) is deprecated. We need to switch to either [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html).

Nowhere I can find this information documented. Can @speed47 please clarify which one is the right one? Thanks!

**Comment by speed47** [comment]
GPL-3.0-only
