### ISSUE TITLE
Raspberry Pi 3 does not support SGX, but this script claims it does

### ISSUE THREAD

**Issue by hotaru2k3** [speed47/spectre-meltdown-checker#255]
when running this script on a Raspberry Pi 3, this script claims it supports SGX and is vulnerable to Foreshadow (SGX), which is obviously not true.
![screenshot_20180928-231012](https://user-images.githubusercontent.com/312461/46240371-6d2ba680-c374-11e8-817e-3f2768ad20df.png)

**Comment by speed47** [comment]
Most probably related to #253, can you try again with the latest `master`?

**Comment by hotaru2k3** [comment]
it looks like that fixed it.
