### ISSUE TITLE
Incorrect virtualization detection

### ISSUE THREAD

**Issue by ErichRitz** [speed47/spectre-meltdown-checker#269]
See comment https://github.com/speed47/spectre-meltdown-checker/commit/906f54cf9ddcbbe279ffff4500fd861c5e36ed23?_pjax=%23js-repo-pjax-container#r31642820

My dmesg is "Booting paravirtualized kernel on bare hardware" but the code checks for "Booting paravirtualized kernel on bare metal".  Thus the code thinks my kernel is virtualized, when it is not.

**Comment by speed47** [comment]
Thanks for the feedback
