### ISSUE TITLE
IBRS is reported as YES even if only IBRS_FW is found in sysfs

### ISSUE THREAD

**Issue by jirislaby** [speed47/spectre-meltdown-checker#275]
You should perhaps do `'\<IBRS\>'` here:
https://github.com/speed47/spectre-meltdown-checker/blob/fc4981bb940f1fac33df01327aa5949299bf1df7/spectre-meltdown-checker.sh#L2698

**Comment by speed47** [comment]
This issue should be fixed with the above commit, please reopen if this is not the case!
