### ISSUE TITLE
Script error (basename)

### ISSUE THREAD

**Issue by fadamo** [speed47/spectre-meltdown-checker#281]
Using the last version of the script, updated via:

./spectre-meltdown-checker.sh --update-builtin-mcedb
Spectre and Meltdown mitigation detection tool v0.40

Fetching MCE.db from the MCExtractor project... DONE
Extracting data... OK MCExtractor database revision 110 dated 2019/05/11
OK local version updated

Now I got this error:

...
....
+ '[' printf = printf ']'
+ '[' -n = -n ']'
+ printf '* SSB mitigation currently active for selected processes: '
* SSB mitigation currently active for selected processes: ++ sed s/status/exe/
++ xargs -n1 readlink -f
++ xargs -n1 basename
++ sort -u
++ tr '\n' ' '
++ sed 's/ $//'
++ grep -El 'Speculation.?Store.?Bypass:[[:space:]]+thread (force )?mitigated' /proc/10094/status /proc/100/status /proc/101/status /proc/10213/status /proc/10266/status /proc/10351/status /proc/103/status /proc/10464/status /proc/104/status /proc/10594/status /proc/105/status /proc/106/status /proc/10824/status /proc/108/status /proc/10969/status /proc/109/status /proc/10/status /proc/11026/status <.....cut....> /proc/9960/status /proc/99/status /proc/9/status /proc/self/status
readlink: missing operand
Try 'readlink --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
+ mitigated_processes=
+ '[' -n '' ']'
+ pstatus yellow NO 'no process found using SSB mitigation through prctl'
+ '[' 0 = 1 ']'
+ case "$1" in
....
...

**Comment by fadamo** [comment]
In my case:

[root@sgsvrdboras31lx:~]# grep -El 'Speculation.?Store.?Bypass:[[:space:]]+thread (force )?mitigated' /proc/9706/status
[root@sgsvrdboras31lx:~]# grep Speculation_Store_Bypass /proc/9706/status
Speculation_Store_Bypass:       thread vulnerable

**Comment by speed47** [comment]
This happened when no process was found using prctl to set ssb mitigation.
Can you confirm latest master fixes your problem?

**Comment by fadamo** [comment]
I confirm the latest release introduces the problem.

**Comment by fadamo** [comment]
Sorry, the version of 6 minutes ago is correct!

Thank you very much
Bye
Fabio
