### ISSUE TITLE
./spectre-meltdown-checker.sh: arithmetic expression: variable conversion error: " capabilities >> 0 & 1 "

### ISSUE THREAD

**Issue by wh0else** [speed47/spectre-meltdown-checker#286]
sudo ./spectre-meltdown-checker.sh 
Spectre and Meltdown mitigation detection tool v0.41

Checking for vulnerabilities on current system
Kernel is FreeBSD 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
CPU is Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz

Hardware check
* Hardware support (CPU microcode) for mitigation techniques
  * Indirect Branch Restricted Speculation (IBRS)
    * SPEC_CTRL MSR is available:  YES 
    * CPU indicates IBRS capability:  YES  (SPEC_CTRL feature bit)
  * Indirect Branch Prediction Barrier (IBPB)
    * PRED_CMD MSR is available:  YES 
    * CPU indicates IBPB capability:  YES  (SPEC_CTRL feature bit)
  * Single Thread Indirect Branch Predictors (STIBP)
    * SPEC_CTRL MSR is available:  YES 
    * CPU indicates STIBP capability:  YES  (Intel STIBP feature bit)
  * Speculative Store Bypass Disable (SSBD)
    * CPU indicates SSBD capability:  YES  (Intel SSBD)
  * L1 data cache invalidation
    * FLUSH_CMD MSR is available:  YES 
    * CPU indicates L1D flush capability:  YES  (L1D flush feature bit)
  * Microarchitecture Data Sampling
    * VERW instruction is available:  NO 
  * Enhanced IBRS (IBRS_ALL)
    * CPU indicates ARCH_CAPABILITIES MSR availability:  YES 
    * ARCH_CAPABILITIES MSR advertises IBRS_ALL capability: [: 0 0 0 0 0 0 0 12: bad number

**Comment by speed47** [comment]
Thanks for your report, there was a bug under BSD in read_msr(), can you try with latest master and see if it fixes your issue? (58a5acf)

**Comment by wh0else** [comment]
Thanks alot! All good now
