### ISSUE TITLE
microsoft windows support

### ISSUE THREAD

**Issue by amayra** [speed47/spectre-meltdown-checker#289]
any hope to support windows ?

**Comment by speed47** [comment]
No, sorry: Windows is so different that nothing of the current script could be reused.
The correct approach under Windows would be to build a native application, so that it can access needed information, which is a completely different approach than the one this script uses.

**Comment by iromeister** [comment]
You can try the MDS tool for a quick overview: [https://mdsattacks.com/](https://mdsattacks.com/)

**Comment by amayra** [comment]
Thank you so much for your kind response i will use this in my linux and try to find another one for my my windows
