### ISSUE TITLE
Is there support for Arch Linux?

### ISSUE THREAD

**Issue by souvikhaldar** [speed47/spectre-meltdown-checker#29]

**Comment by testos77** [comment]
Archlinux is supported, it's a shell script
`sudo bash spectre-meltdown-checker.sh --kernel /boot/Image --config /boot/.... `

**Comment by speed47** [comment]
Indeed, it is.

If you want to test your current system with the current running kernel, you can just call the script without any option, it'll infer the rest of the informations:

`sudo ./spectre-meltdown-checker.sh`

Closing the issue, feel free to reopen if it doesn't work under your Arch system.
