### ISSUE TITLE
extract_kernel: if one decompress tool is missing, it won't try the following tools and return directly

### ISSUE THREAD

**Issue by lillylee** [speed47/spectre-meltdown-checker#297]
My testing kernel image is compressed by lz4 and my testing device doesn't install lzop tool. both try_decompress and extract_kernel return directly without try the following lz4 tool; see the debugging logs:
(debug) check_kernel: ret=0 size=13109408 sections=0 warnings=readelf: Error: Not an ELF file - it has the wrong magic bytes at the start/
(debug) check_kernel: ... file is invalid
(debug) try_decompress: looking for gunzip magic in /lib/kernel/org.clearlinux.native.5.1.16-795
(debug) try_decompress: magic for gunzip found at offset 3358051:xy
(debug) try_decompress: decompression with gunzip failed (err=1)
(debug) try_decompress: magic for gunzip found at offset 3980186:xy
(debug) try_decompress: decompression with gunzip failed (err=1)
(debug) try_decompress: magic for gunzip found at offset 12002045:xy
(debug) try_decompress: decompression with gunzip failed (err=3)
(debug) try_decompress: looking for unxz magic in /lib/kernel/org.clearlinux.native.5.1.16-795
(debug) try_decompress: magic for unxz found at offset 10673539:abcde
(debug) try_decompress: decompression with unxz failed (err=1)
(debug) try_decompress: looking for bunzip2 magic in /lib/kernel/org.clearlinux.native.5.1.16-795
(debug) try_decompress: looking for unlzma magic in /lib/kernel/org.clearlinux.native.5.1.16-795
(debug) try_decompress: magic for unlzma found at offset 7062355:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: magic for unlzma found at offset 7106024:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: magic for unlzma found at offset 8964810:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: magic for unlzma found at offset 11308176:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: magic for unlzma found at offset 11346484:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: magic for unlzma found at offset 11348963:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: magic for unlzma found at offset 11646092:xxx
(debug) try_decompress: decompression with unlzma failed (err=1)
(debug) try_decompress: looking for lzop magic in /lib/kernel/org.clearlinux.native.5.1.16-795
(debug) try_decompress: magic for lzop found at offset 9042313:xy

kernel_err='missing '''lzop''' tool, please install it, usually it'''s in the '''lzop''' package'

* Kernel supports RSB filling:  UNKNOWN  (kernel image missing)

If i change the return value of try_decompress to non-zero value upon missing tool, it will continue try lz4 and decompress the kernel image successfully.
diff --git a/spectre-meltdown-checker.sh b/spectre-meltdown-checker.sh
index 8ed1ddc9f0ef..b2451ee98df2 100755
--- a/spectre-meltdown-checker.sh
+++ b/spectre-meltdown-checker.sh
@@ -1069,7 +1069,7 @@ try_decompress()
 		_debug "try_decompress: magic for $3 found at offset $pos"
 		if ! command -v "$3" >/dev/null 2>&1; then
 			kernel_err="missing '$3' tool, please install it, usually it's in the '$5' package"
-			return 0
+			return 1
 		fi
 		pos=${pos%%:*}
 		# shellcheck disable=SC2086
--

**Comment by speed47** [comment]
Latest commit introduce a better tolerance over missing decompression tools, please reopen if the issue persist. Thanks!
