### ISSUE TITLE
TSX Asynchronous Abort (ZombieLoad V2)

### ISSUE THREAD

**Issue by Matthew-Bradley** [speed47/spectre-meltdown-checker#313]
Hi,

A new speculative vulnerability has come to light. It's a variant of ZombieLoad that Intel were warned about but failed to patch. https://www.phoronix.com/scan.php?page=news_item&px=ZombieLoad-TAA-Announced

This just really isn't their day, what with the skylake-and-later jump condition code errata that just came out too. (https://www.phoronix.com/scan.php?page=article&item=intel-jcc-microcode&num=1 though this one it's speculative; it just requires a microcode update and performance hit)

**Comment by hardfalcon** [comment]
TAA support was already added by https://github.com/speed47/spectre-meltdown-checker/pull/312.

**Comment by speed47** [comment]
Support is still in early stage and will be amended in the following hours/days as more people test it, but yes, it's available in the master branch.

Intel released a bunch of fixes for a bunch of CVEs on all their product range today, seems like we'll have to be accustomed to this new way, batch-releasing CVEs on a regular basis (a la Microsoft "patch tuesday").

**Comment by speed47** [comment]
v0.43 released, please open a new issue if any problem arises. Thanks!
