### ISSUE TITLE
new variant of zombieload

### ISSUE THREAD

**Issue by asarubbo** [speed47/spectre-meltdown-checker#315]
From https://zombieloadattack.com :

With November 14th, 2019, we present a new variant of ZombieLoad that enables the attack on CPUs that include hardware mitigations against MDS in silicon. With Variant 2 (TAA), data can still be leaked on microarchitectures like Cascade Lake where other MDS attacks like RIDL or Fallout are not possible. Furthermore, we show that the software-based mitigations in combinations with microcode updates presented as countermeasures against MDS attacks are not sufficient.

We disclosed Variant 2 to Intel on April 23th, 2019, and communicated that the attacks work on Cascade Lake CPUs on May 10th, 2019. On May 12th, 2019, the variant has been put under embargo and, thus, has not been published with the previous version of our ZombieLoad attack on May 14th, 2019.

If you want to learn more about the new variant, we welcome you to read the updated version of our publication or checkout Intel's One Pager, Deep Dive, and Security Advisory Disclosure.

**Comment by speed47** [comment]
The main issue for ZombieLoad V2 is #313, closing as dupe (feel free to repost your comment on #313 if you think it helps giving some context!)
