### ISSUE TITLE
Custom kernel boot images not found in live mode

### ISSUE THREAD

**Issue by Ryujinra** [speed47/spectre-meltdown-checker#317]
On arch, with a kernel with a custom name such as `vmlinuz-custom-linux`, the script is not able to detect the currently active kernel image in live mode.

I've been working around it with the `--kernel` flag, but this forces me to use offline mode and supply an extracted kernel config from /proc/config.gz, and then the script is unable to report on whether certain mitigations are active or not, so this is less than ideal.

My /proc/cmdline contains the following relevant boot text:
`... \boot\vmlinuz-custom-linux ...`

**So, would it be possible to either parse `/proc/cmdline/` to detect these arbitrarily named kernels (maybe anything in the kernel cmdline that is on the boot partition but doesn't start with `initrd=`), or at least allow us to explicitly supply just the location of the kernel in `live` mode (and automatically use the currently active config and map in procfs)?**

Thanks for your work.

**Comment by speed47** [comment]
There is logic in the script to try to autodetect kernel image locations in several distros.
Could you share your whole /proc/cmdline to see if I could add what's needed in the script to autodetect those cases (if they're Arch standardized way of compiling custom kernels).

It's always useful to be able to override autodetection in any case, while remaining in live mode. Could you try the `livemanual` branch and see if it fixes your use case? Just explicitly add `--live` and the location of your kernel to `--kernel`, if --map and/or --config are not specified, they'll still be autodetected

**Comment by Ryujinra** [comment]
The `livemanual` branch works perfectly as far as I can tell with `--live` and `--kernel` specified. 

Mostly default besides adding the intel-ucode img, but here is the full cmdline absent the long UUID storage string:

`pti=on page_alloc.shuffle=1 \boot\vmlinuz-custom-linux root=UUID={BIGSTRING} rw quiet initrd=/boot/intel-ucode.img initrd=\boot\initramfs-custom-linux.img`

**Comment by speed47** [comment]
I think it's unique, or at least not a global standard: I've never seen the path of the kernel indicated in the cmdline, and clearly not replacing /'s with \'s! But if at least Arch uses this, it's still worth implementing.
I've just updated the `livemanual` branch, can you update your local copy and confirm it does detects your kernel without `--kernel`?

**Comment by Ryujinra** [comment]
Doesn't appear to work.

I looked at your commit and ran `cat /proc/cmdline | grep -Eow "\\\\[\\\\a-zA-Z0-9_.-]+" | tr "\\\\" "/"` to test your pattern matching.

It returns **both** the kernel image and ramfs:

`/boot/vmlinuz-linux-custom`
`/boot/initramfs-linux-custom.img`

My guess is we need to omit matches containing `initramfs`, that start with `initrd=`, end with `.img`, or some combination of the three. Actually, as a more general approach, it may be more appropriate to only match the part of the cmdline that starts with \boot\ but is preceded by a blankspace.

**Comment by speed47** [comment]
I forgot that `=` was not part of `\w` in grep so the `-w` option is not enough to rule out the `initrd=` section.
Pushed a fixed version, can you retry? (confirmed working on my side by mocking)

**Comment by Ryujinra** [comment]
Hmm, the pattern works now and correctly returns my kernel location if I pipe the output of /proc/cmdline into the grep/tr command, but the script itself still can't find it for some reason.

Behavior is the same as before where the script just complains about no kernel img in /boot.

**Comment by speed47** [comment]
Just figured this typo, yes it should be /proc/cmdline of course. Oh well, my brain doesn't seem to be functioning on Sundays...
Fixed.

**Comment by Ryujinra** [comment]
Yep, confirmed working as expected now with latest `livemanual` branch. I'll close this now as both features (allow supplying kernel explicitly in --live mode and auto-detection of custom kernel names on Arch) have been added and appear to work properly.
