### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sylvestre** [speed47/spectre-meltdown-checker#330]
With 
https://github.com/speed47/spectre-meltdown-checker/pull/312
https://github.com/speed47/spectre-meltdown-checker/pull/327
maybe it is time to do a new release?
See also http://bugs.debian.org/944686

**Comment by speed47** [comment]
Exactly, which is why I'm not adding more features (and bugs) before next release, I just want to be sure both TAA and MCEPSC are as stable as possible (i.e. no known bug reported). Last fix is less than one hour old ;)
Target for next release is this week!

**Comment by speed47** [comment]
v0.43 released :)

**Comment by sylvestre** [comment]
Merci!
