### ISSUE TITLE
Are we sure this works?

### ISSUE THREAD

**Issue by ewwhite** [speed47/spectre-meltdown-checker#34]
Unpatched physical machine on Sandy Bridge CPU and EL7 shows:

    STATUS:  NOT VULNERABLE  (your CPU vendor reported your CPU model as not vulnerable)

All of my EL6 virtual machines on VMware show:

    STATUS:  NOT VULNERABLE  (your CPU vendor reported your CPU model as not vulnerable)

Physical Sandy Bridge CPU and EL6 system shows:

    STATUS:  VULNERABLE  (IBRS hardware + kernel support OR kernel with retpoline are needed to mitigate the vulnerability)

**Comment by speed47** [comment]
Doh, the recent commit 68961f98c2784a0fda358202fc041345853d1709 has a broken logic, thanks for noticing.
Fixing...

**Comment by speed47** [comment]
Please test v0.20

**Comment by mhenderson-so** [comment]
My initial tests seem to show that the script is responding appropriately now. Thanks for the quick update!

**Comment by ewwhite** [comment]
Thank you. This works for me now.
