### ISSUE TITLE
ARM v8 model 0xd0c support

### ISSUE THREAD

**Issue by garick560** [speed47/spectre-meltdown-checker#371]
Hi,
now script doesn't support ARM v8 model 0xd0c. Could you fix this issue ASAP?

Thanks,
Igor

**Comment by speed47** [comment]
Added support for 0xd0c (Neoverse N1) and 0xd0d (Cortex A77) in the `arm` branch. Could you test it?
https://github.com/speed47/spectre-meltdown-checker/blob/arm/spectre-meltdown-checker.sh

**Comment by garick560** [comment]
Hi,
It works for me. Thanks a lot!

**Comment by speed47** [comment]
Thanks, merged
