### ISSUE TITLE
AMD microcode seems not up to date for Ryzen 4500U

### ISSUE THREAD

**Issue by mcloaked** [speed47/spectre-meltdown-checker#389]
Running the current spectre checker for my AMD Ryzen 4500U machine I get the ouput including:

CPU microcode is the latest known available version:  NO  (latest version is 0x8600106 dated 2020/06/19 according to builtin firmwares DB v165.20201021+i20200616)

And if I check my boot log the version loaded (and it tries to update early during boot to the latest from from the amd-ucode.img file:

$ sudo journalctl -b | grep microcode
Jan 13 19:57:59 saplinux kernel: microcode: CPU0: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU1: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU2: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU3: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU4: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU5: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU6: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: CPU7: patch_level=0x08600104
Jan 13 19:57:59 saplinux kernel: microcode: Microcode Update Driver: v2.2.

Yet at https://github.com/platomav/CPUMicrocodes it shows:

AMD  Updated to MCE DB r168  2 months ago

Does that mean that the checker script is not up to date concerning AMD cpu's? Also this seems to imply that the latest microcode in the amd-ucode package is also not up to date.

Can the spectre checker script be brought fully up to date with the firmwares DB?

**Comment by speed47** [comment]
The `--update-fwdb` switch is there exactly for this: it'll update your local db from the latest MCEdb and Intel repos.
