### ISSUE TITLE
The "Example of script output" section of README is dead

### ISSUE THREAD

**Issue by foxpy** [speed47/spectre-meltdown-checker#390]
All three links there are broken and return empty HTML with "Not Found" message.

Maybe these samples should be stored in repo itself?

**Comment by szepeviktor** [comment]
Yes.

```
## Example of script output

- Intel Haswell CPU running under Ubuntu 16.04 LTS

![haswell](https://framapic.org/1kWmNwE6ll0p/ayTRX9JRlHJ7.png)

- AMD Ryzen running under OpenSUSE Tumbleweed

![ryzen](https://framapic.org/TkWbuh421YQR/6MAGUP3lL6Ne.png)

- Batch mode (JSON flavor)

![batch](https://framapic.org/HEcWFPrLewbs/om1LdufspWTJ.png)
```

**Comment by szepeviktor** [comment]
"Framapic" was shut down.

**Comment by speed47** [comment]
Salvaged the images from The Wayback Machine:
![smc1](https://user-images.githubusercontent.com/218502/108764885-6dcfc380-7553-11eb-81ac-4d19060a3acf.png)
![smc2](https://user-images.githubusercontent.com/218502/108764896-70321d80-7553-11eb-9dd2-fad2a0a1a737.png)
![smc3](https://user-images.githubusercontent.com/218502/108764902-71634a80-7553-11eb-9678-fd304995fa64.png)

Fixing the README.

**Comment by szepeviktor** [comment]
@foxpy Could you close this one?

**Comment by foxpy** [comment]
> @foxpy Could you close this one?

Yep!
