### ISSUE TITLE
False Positive 0x406c3 Spectre v3a

### ISSUE THREAD

**Issue by theAeon** [speed47/spectre-meltdown-checker#393]
![image](https://user-images.githubusercontent.com/9099529/110087883-371f5780-7d62-11eb-8b6c-5bafccacdcee.png)
![image](https://user-images.githubusercontent.com/9099529/110088150-7baaf300-7d62-11eb-9e67-73e614b0418c.png)
![image](https://user-images.githubusercontent.com/9099529/110088110-70f05e00-7d62-11eb-8f9b-ddfc00747b7a.png)

According to intel's database, this cpuid is not vulnerable to spectre v3a. The tool reports fully up-to-date microcode as vulnerable.

**Comment by speed47** [comment]
Thanks for the headsup, their `xlsx` file is very interesting, I'll build some helper to parse the file and ensure the script is completely in sync with this data.

**Comment by saelic** [comment]
Hello, any progress on this issue?

**Comment by speed47** [comment]
Implemented in #461
