### ISSUE TITLE
BTRFS transparent compression | Unknown kernel compression format

### ISSUE THREAD

**Issue by Ricky-Tigg** [speed47/spectre-meltdown-checker#395]
**OS:** Fedora 34

**Issue:** Unknown kernel compression format
```
$ su -c 'spectre-meltdown-checker -v --paranoid --explain'
Spectre and Meltdown mitigation detection tool v0.44
[...]
Kernel is Linux 5.11.7-300.fc34.x86_64 #1 SMP Wed Mar 17 18:43:52 UTC 2021 x86_64
CPU is Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Will use kernel image /boot/vmlinuz-5.11.7-300.fc34.x86_64
Will use kconfig /lib/modules/5.11.7-300.fc34.x86_64/config
Will use System.map file /proc/kallsyms
Couldn't extract the kernel image (kernel compression format is unknown or image is invalid), accuracy might be reduced
```
Hello. The restriction faced while extracting has root in the following change: Since **version 33**, Fedora made _BTRFS_ the default file system for desktop variants. Since **version 34**, Fedora enables **transparent compression** in order to increase disk space which increases the lifespan of flash-based media by reducing write amplification for solid-state disks. This compression improves the performance of read-write operations applying to larger files, which has the potential to bring appreciable time efficiency into work flows.

**Comment by speed47** [comment]
It shouldn't be a problem as btrfs compression is done at the filesystem level hence transparent to the apps. However this Fedora version might come with a kernel compressed with some new algorithm. I'll have a look into it.

**Comment by speed47** [comment]
It's compressed with zstd, and you probably don't have the zstd tools installed. The error can be seen in very verbose mode (`-v -v`), I'll propose a patch to make it user-visible, as this is already the case when the `binutils` package is missing.

**Comment by speed47** [comment]
Can you try this branch?
https://raw.githubusercontent.com/speed47/spectre-meltdown-checker/unzstd/spectre-meltdown-checker.sh

**Comment by Ricky-Tigg** [comment]
_zstd_  – That was a relevant aspect worth mentioning. I omitted it in the report. That extra '`-v`' suits so well for further investigation; That is correct, i did not have _Zstandard_ compression library installed at that time as indicate it messages _zstd_ as part of messages `(debug) try_decompress: decompression with <compression algorithm> failed (err=1)`, in which there is no mention of _zstd_. Once installed – as version **1.4.9** – , the issue was no longer observable.

Output resulting from the execution of your Bash script:
```
$ sudo ./spectre-meltdown-checker_0.44+ 
Spectre and Meltdown mitigation detection tool v0.44+

Checking for vulnerabilities on current system
Kernel is Linux 5.11.8-300.fc34.x86_64 #1 SMP Mon Mar 22 01:33:25 UTC 2021 x86_64
CPU is Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Hardware check
[...]
```

**Comment by speed47** [comment]
>  `(debug) try_decompress: decompression with <compression algorithm> failed (err=1)`, in which there is no mention of _zstd_. 

There are a bunch of lines like this, because in a compressed kernel, there are a lot of "magic bytes" appearing, that might indicate the beggining of a compressed area, but as those magic bytes are short, they also appear just by chance, so that's what these lines mean. You probably had another line saying `missing 'zstd' tool, please install it`.


> $ sudo ./spectre-meltdown-checker_0.44+ 
> Spectre and Meltdown mitigation detection tool v0.44+
> 
> Checking for vulnerabilities on current system
> Kernel is Linux 5.11.8-300.fc34.x86_64 #1 SMP Mon Mar 22 01:33:25 UTC 2021 x86_64
> CPU is Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

If you try this new version, without `zstd` installed, it should tell you (without needing to add any `-v`)

**Comment by Ricky-Tigg** [comment]
Script run as it is. How to interpret?
> without needing to add any -v

Output resulting from the execution of your Bash script, while zstd being not installed:
```
$ sudo ./spectre-meltdown-checker.sh
Spectre and Meltdown mitigation detection tool v0.44+

Checking for vulnerabilities on current system
Kernel is Linux 5.11.8-300.fc34.x86_64 #1 SMP Mon Mar 22 01:33:25 UTC 2021 x86_64
CPU is Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Hardware check
[...]
```
It remains unchanged doesn't it?

**Comment by speed47** [comment]
It should be further down below, when the script would need to read the uncompressed kernel, such as:

`* TAA mitigation is supported by kernel:  UNKNOWN  (missing 'unzstd' tool, please install it, usually it's in the 'zstd' package)`

**Comment by Ricky-Tigg** [comment]
Confirmed | line 152.
