### ISSUE TITLE
Add options to pick specific variant to test

### ISSUE THREAD

**Issue by matglas** [speed47/spectre-meltdown-checker#40]
I'm running this script now against a cluster. Would it be possible to add a --variant 1,2,3 to pick what to test for? This way I can incrementally see what nodes still need to be patched based on the releases that are happening.

**Comment by speed47** [comment]
Can do, should be easy enough

**Comment by speed47** [comment]
Can you test the `opt_variant` branch ?

**Comment by lasse-kristensen** [comment]
Works fine for me on centos 6, centos7 and ubuntu 16.04, thanks.

**Comment by matglas** [comment]
Works fine for me too. Ran it on 16.04.

**Comment by matglas** [comment]
Thank you for this addition.

**Comment by matglas** [comment]
Here is my work to use the script in an Ansible play that checks hosts https://github.com/VDMi/ansible-spectre-meltdown-checker for those that want to use it.

**Comment by speed47** [comment]
Perfect! I'm waiting for PR #41 to be merged before merging this one, as I was forced to reindent most of the code, and it would conflict. You can expect it later today :)

**Comment by speed47** [comment]
Merged
