### ISSUE TITLE
Extracting MCEdb data... Error: no such column: date

### ISSUE THREAD

**Issue by z-image** [speed47/spectre-meltdown-checker#400]
spectre-meltdown-checker.sh --update-fwdb is failing due to https://github.com/platomav/MCExtractor/commit/48d55666a3034118233fb4e76a6577173e4c6377

It seems 'Date' has been split into 'Year', 'Day', 'Month'.

**Comment by speed47** [comment]
Confirmed, the "date" column has been completely removed from the MCE table, it's not an issue, it was just used to tag the version number. Pushing a fix in a few minutes.
