### ISSUE TITLE
Docker build lacks zstd

### ISSUE THREAD

**Issue by brlin-tw** [speed47/spectre-meltdown-checker#433]
Running `docker-compose up` reveals several UNKNOWN results like the following:

```
spectre-meltdown-checker    | * iTLB Multihit mitigation is supported by kernel:  UNKNOWN  (missing 'unzstd' tool, please install it, usually it's in the 'zstd' package)
```

**Comment by speed47** [comment]
Hello, and thanks for your report.
Could you try the `docker` branch and confirm it does fixes the problem?

**Comment by brlin-tw** [comment]
I can no longer reproduce this issue in the revision of the `docker` branch.
