### ISSUE TITLE
--update-fwdb fails with errors

### ISSUE THREAD

**Issue by gene-git** [speed47/spectre-meltdown-checker#443]
Starting today the --update-fwdb option fails:
     
    Extracting MCEdb data... OK MCExtractor database revision 259
    Integrating Intel firmwares data to db... Error: in prepare, no such column: intel
      NTO Intel (origin,cpuid,version,yyyymmdd)  ALUES ("intel","00000650","00000045
                                          error here ---^

**Comment by speed47** [comment]
I can't reproduce the issue you have:
```
$ ./spectre-meltdown-checker.sh --update-fwdb
Spectre and Meltdown mitigation detection tool v0.45-2-gbea5cfc

Fetching MCE.db from the MCExtractor project... DONE
Fetching Intel firmwares... DONE
Extracting MCEdb data... OK MCExtractor database revision 260
Integrating Intel firmwares data to db... DONE (version 20230215)
Building local database... DONE (version 260+i20230215)
```

Do you still have the problem as of now? (I might have been a transient problem with the upstream fwdb)

**Comment by gene-git** [comment]
Yes - did fresh clone of repo - same problem.

Could it version of base or sqlite3 maybe?

On Archlinux using these versions:
  bash 5.1.016-3
  sqlite 3.41.0-1

**Comment by gene-git** [comment]
Only change from my prior is version is now 260 but  error remains same.

**Comment by speed47** [comment]
I can reproduce with Archlinux in a docker, checking...

**Comment by gene-git** [comment]
I  confirm its works fine - my builds will pick it up once it makes it to master.

thank you again.
I left it to you to close this one if thats ok.
