### ISSUE TITLE
Only /proc/sys/kernel/ibrs_enabled present in Opensuse tumbleweed

### ISSUE THREAD

**Issue by xxxmurky** [speed47/spectre-meltdown-checker#45]
I am running Opensuse tumbleweed with kernel 4.14.12-1 (which is patched already), debugfs is mounted under /sys/kernel/debug but there is no such file as /sys/kernel/debug/ibrs_enabled or /sys/kernel/debug/x86/ibrs_enabled.  However ibrs_enabled is present here:

/proc/sys/kernel/ibrs_enabled

...and it contains a value of 1.

Not sure if other distros behave the same, just thought I'd let you know.

**Comment by speed47** [comment]
Distros backport the patches and sometimes they change stuff. I'm interested in supporting the maximum amount of distros possible!

Can you try to echo 2 in it ? (it should enable ibrs for kernel + userspace). Just to be sure that they just changed the location of this file, and not the meaning of the values it contains.

**Comment by speed47** [comment]
In the meantime, can you try the opensuse branch?

**Comment by xxxmurky** [comment]
Yes, I can echo 2 into /proc/sys/kernel/ibrs_enabled.  Opensuse branch works perfectly! Also, checking with sysctl I can see the value updated:

`m-comp:~/spectre-meltdown-checker # sysctl -a|grep ibrs
kernel.ibrs_dump = 0
kernel.ibrs_enabled = 1
m-comp:~/spectre-meltdown-checker # echo 2 >/proc/sys/kernel/ibrs_enabled
m-comp:~/spectre-meltdown-checker # sysctl -a|grep ibrs
kernel.ibrs_dump = 0
kernel.ibrs_enabled = 2
`
All seems OK! :)

**Comment by speed47** [comment]
Thanks, merging
