### ISSUE TITLE
Blacklist microcode 0x119 and 0x4119 for Raptor Lake CPUs?

### ISSUE THREAD

**Issue by cranderson** [speed47/spectre-meltdown-checker#475]
While the symptoms appear so far to be only on Windows, should we blacklist this microcode?  I have this processor and microcode and haven't experienced any issues, but maybe some people dual-boot into Windows.

"CPUs with the IDs 0xB0671, 0xBO6A2 or 0xBO6A3 are affected. This is the Raptor Lake desktop flagship with 8 P and 16 E cores as well as various mobile CPUs. Processors with IDs 0xBO6F2 and 0xBO6F5 are not affected by the BSOD error.
[...]
In a statement, Intel reportedly stated that the latest microcode versions 0x119 and 0x4119 for Raptor Lake CPUs, released in June of this year, do not have consistent values ​​for the GDS_NO flag between the P and E cores. And according to Intel, the affected processors with microcode versions 0x119 and 0x4119 can experience BSOD errors
[...]
Intel is now preparing fresh microcode to completely fix the BSOD problem. This code should then have the version numbers 0x11D and 0x411D and be published for the affected CPUs of the 13th core generation."
[https://www.aroged.com/2023/09/06/unsupported-cpu-now-intel-is-probably-to-blame-for-the-blue-screens/](url)

**Comment by speed47** [comment]
Thanks, I've added these 3 microcode revisions to the list :)
