### ISSUE TITLE
Error with --update-builtin-fwdb  :  Integrating Intel firmwares data to db... Error: in prepare, no such column: intel

### ISSUE THREAD

**Issue by OscarFrog** [speed47/spectre-meltdown-checker#486]
Hi,
When i launch the script with "-update-builtin-fwdb" in Fedora 39 i have an error :

Fetching MCE.db from the MCExtractor project... DONE
Fetching Intel firmwares... DONE
Extracting MCEdb data... OK MCExtractor database revision 283
Integrating Intel firmwares data to db... Error: in prepare, no such column: intel
  DELETE FROM "Intel" WHERE "origin" != "intel" AND "cpuid" = '00000650';
                          error here ---^

then, an other one :
CPU microcode is the latest known available version:  UNKNOWN  (latest microcode version for your CPU model is unknown)

Thanks :)

**Comment by fmauNeko** [comment]
There is a typo at https://github.com/speed47/spectre-meltdown-checker/blob/master/spectre-meltdown-checker.sh#L1158 introduced in #483, `WHERE \"origin\" != \"intel\"` should be `WHERE \"origin\" != 'intel'`.

**Comment by OscarFrog** [comment]
Hi,
It works ! Thanks :)

**Comment by OscarFrog** [comment]
Hi,
i made a little script :

```
#!/bin/bash
rm ./spectre-meltdown-checker.sh
wget https://meltdown.ovh/ -O spectre-meltdown-checker.sh
sed -i 's/WHERE \\"origin\\" != \\"intel\\"/WHERE \\"origin\\" != \x27intel\x27/g' ./spectre-meltdown-checker.sh
chmod +x ./spectre-meltdown-checker.sh
sudo ./spectre-meltdown-checker.sh --update-builtin-fwdb
sudo ./spectre-meltdown-checker.sh
```

**Comment by speed47** [comment]
@OscarFrog @fmauNeko ,

Thanks for the report and pointing out the typo, that's obviously an error but my version of `sqlite3` doesn't yell at me with this typo, which is why it went undetected!
