### ISSUE TITLE
root / superuser

### ISSUE THREAD

**Issue by vap0rtranz** [speed47/spectre-meltdown-checker#52]
Please update doc/disclaimer that root/superuser privileges are required to get accurate results from the script.  Normal user results aren't accurate.  This is because /sys is checked by the script and owned by root on most (all?) Linuxes.

**Comment by speed47** [comment]
There should be a red warning at the begining of the script if you're running it unprivileged, did you have it?
It doesn't cost anything to add a notice about this in the readme as you're suggesting, though.

**Comment by vap0rtranz** [comment]
Ah, I did not see that notice, probably b/c I didn't get any warnings/errors as standard user.  Just got inaccurate results.

I'll close this.
