### ISSUE TITLE
Incorrect AMD not vulnerable flag?

### ISSUE THREAD

**Issue by iam-TJ** [speed47/spectre-meltdown-checker#69]
The code in is_cpu_vulnerable() for AMD CPUs sets

variant1=0

Shouldn't this be variant3 a.k.a. Meltdown?

**Comment by speed47** [comment]
This is exactly the root cause of a bad commit I've made at first (corrected 1 hour later).
This is a shell script, 0 is true :)

**Comment by iam-TJ** [comment]
Ahh, then why not do =true or =false which evaluate to /bin/true or /bin/false respectively?

That's what I do when working with true/false boolean values to save the confusion of mis-reading what are boolean values (has 2 states) incorrectly.

**Comment by speed47** [comment]
Hmm, why not, it would force us to execute those commands at the end of the func to get the proper return code however, but as performance is not that critical in this script, it's probably fine

**Comment by speed47** [comment]
Closing this, as the comments in the function have been corrected, and the code simplified.
Hopefully this is more readable now ;)
