### ISSUE TITLE
CPU flags "pcid" and "invpcid"

### ISSUE THREAD

**Issue by mike155** [speed47/spectre-meltdown-checker#74]
Thanks for your wonderful tool!

In the last days, I performed various performance tests and measured performance degradation due to Meltdown patches in the kernel, especially in virtual machines. The result is, that the degree of performance degradation is dependent on CPU flag "pcid" and probably also on "invpcid". It might be worth to show presence of these CPU flags in your tool.

I posted my results here:
- https://forums.gentoo.org/viewtopic-p-8169200.html#8169200
- https://forums.gentoo.org/viewtopic-p-8169908.html#8169908

Willy Tarreau also saw this dependency on pcid/invpcid in virtual machines:
- https://marc.info/?t=151532047900001&r=1&w=2

A test could be something like this:

```
for flag in pcid invpcid 
do 
    echo -n "${flag}: "
    if grep -m 1 "^flags" /proc/cpuinfo | grep -q " ${flag}"
    then
        echo "available"
    else
        echo "NOT available"
    fi
done
```

**Comment by speed47** [comment]
Good idea, I've implemented this in the latest `master` version.
To avoid confusing people and keep the default output of the script as clear as possible, this is only shown in verbose mode.
