### ISSUE TITLE
Additional flags

### ISSUE THREAD

**Issue by theoren** [speed47/spectre-meltdown-checker#86]
It would be useful to add 
 --color
 --global
 --no-global

The use case is minimal update making the script default to no-color and no-global exit code
Both may avoid breaking stuff under certain settings

**Comment by speed47** [comment]
If I understand correctly, you'd like to change the default to get no colors. People are used to the colored output by now and I don't want to change that. It's also more user friendly in any case, and `--no-color` is here for any scripted need.

As for the exit codes, they're clearly documented, could you be more specific?

**Comment by speed47** [comment]
No news, closing. Please reopen if needed.
