### ISSUE TITLE
Linux Mint 18.3 // ubuntu 16.04 LTS - Why vulnerable to attack 1&2

### ISSUE THREAD

**Issue by razzor1984** [speed47/spectre-meltdown-checker#87]
Hello, 

im running linux mint 18.3 which is basically  a ubuntu 16.04 Lts with microcode intel-microcode 3.20180108.0~ubuntu16.04.2 update an Kernel: 4.13.0-26-generic (which is patched)
Why am i vulnerable to spectre 1?
only 29 opcodes found, should be >=70 -- Vulnerable 
Spectre variante 2: Vulnerable 
IBRS hardware + Kernel support OR Kernel with retpoline are needed to mitigate the vulnerability

best regards Razzor

**Comment by speed47** [comment]
Do you have any evidence that Ubuntu patched their kernel for Spectre 2 and 1 ? AFAIK There's no patch upstream yet for Spectre 1, and Spectre 2 is being worked on actively.
From this link https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/SpectreAndMeltdown it seems that only testing kernels very recently released have the Spectre 2 patch

**Comment by razzor1984** [comment]
I have read that 4.13.0-25 should be patche for spectre and Meltdown 
Ok i switch to the newest 4.15 RC - thanks.
best regards Razzor

**Comment by speed47** [comment]
I'm closing this issue, don't hesitate to reopen it if needed!
