### ISSUE TITLE
Skyfall and Solace incoming

### ISSUE THREAD

**Issue by waja** [speed47/spectre-meltdown-checker#99]
Hi here,

just a quick note, there are two additional issues incoming: Skyfall and Solace
Still no logos, but I guess this is just a matter of time and this will getting serious. Check out skyfallattack.com.

Cheers, Jan.

**Comment by speed47** [comment]
Hello Jan,

Yes, I saw that today.
This might or might not be true, maybe FUD or a prank, or end up being something real. I tend to think this is more a prank than anything else at this stage, but let's be cautious and just wait to see what happens.

(closing this issue to tidy up the issues list, as there's nothing to do for now, except checking what comes out of this website!)

**Comment by waja** [comment]
> just a quick note, there are two additional issues incoming: Skyfall and Solace
Still no logos, but I guess this is just a matter of time and this will getting serious. Check out skyfallattack.com.

Looks like a trap or something. But nothing which should deserve our attention.
